### ISSUE TITLE
Typo in variable name KKSP2 in NIFTI_NORDIC.m

### ISSUE THREAD

**Issue by dvm-shlee** [SteenMoeller/NORDIC_Raw#18]
https://github.com/SteenMoeller/NORDIC_Raw/blob/0aac63cd8907db8f6963bced63d34903cc545535/NIFTI_NORDIC.m#L288

**Description:**
I noticed a typo in the variable name KKSP2 in the NIFTI_NORDIC.m file. On line 288 of the file, KKSP2 is used, but it is not defined or used anywhere else in the code. It appears that this variable should actually be KSP2 based on its usage in other parts of the code.

I wanted to confirm if this typo could potentially cause any issues with the final processed data. If there are no other dependencies or calculations specifically related to KKSP2, it should be safe to replace it with KSP2 for consistency.

**Steps to Reproduce:**

Open the NIFTI_NORDIC.m file.
Go to line 288.

**Expected Behavior:**
The variable name KKSP2 should likely be KSP2 based on its usage in other parts of the code.

**Comment by SteenMoeller** [comment]
It can be changed, and should have limited implication on the performance. The part of the code is used for getting at the gfactor estimate and not the signal. For the signal it would have negative effects. I don't remember if there was a performance reason for why I exclude the mean phase in the gfactor estimation part.

**Comment by dvm-shlee** [comment]
Thank you for your quick response.

I wanted to clarify whether the part of the code that uses the variable KKSP2 is actually excluded by assigned to a new variable. I'm seeking clarification on how a variable that has not been explicitly initialized before can be used in the code. then can it be also commented out (for line 286-290)?

Apologies if this is a basic question, but I want to ensure my understanding is correct as I am not very familiar with MATLAB. Thank you for your patience in helping me clarify this point.
