### ISSUE TITLE
NORDIC ERROR on few slices fMRI

### ISSUE THREAD

**Issue by icaroafoliveira** [SteenMoeller/NORDIC_Raw#2]
Dear NORDIC developers,

I am trying to run NORDIC on fMRI data (BOLD and VASO). I tried a couple of protocols, and in one of them, I found the following error.

_Index in position 3 is invalid. Array indices must be positive integers or logical values._

 function --> subfunction_loop_for_NVR_avg_update

line 866--> KSP2_tmp=KSP2a(:,[1:w2]+(n2-1),[1:w3]+(n3-1),:);

Apparently in the second loop, w3 ==> (ARG.kernel_size(3)) change to a number that is bigger than my # slices (12 slices).

Do you know what I can do to fix that?

Best regards, 

Ícaro Oliveira

**Comment by SteenMoeller** [comment]
Dear   Ícaro Oliveira

Thanks for trying the code, and sorry that your are having issues.
I will update the code tomorrow when I am back from vacation.
In the meantime, for a situation like this, one can manually specify the
patch size.
We use the guiding principle that the product of the three spatial
dimensions should be 11 times the temporal dimension.

To specify manually the patch size, one can use
  ARG.kernel_size_PCA=[n1 n2 n3]

In your case, then n3=12, and n1 and n2 have to be selected
such that roughly n1*n2*n3~=  11*temproal dimension
We will incorporate this into the code, such that it happens automatically

Steen
Steen
