### ISSUE TITLE
Index of first dropped singular value is set to number of dropped values in NORDIC step

### ISSUE THREAD

**Issue by tsalo** [SteenMoeller/NORDIC_Raw#23]
In the denoising step, the first dropped singular value (`t`) is set to the number of dropped singular values (`idx`) when `isempty(soft_thrs)`:

https://github.com/SteenMoeller/NORDIC_Raw/blob/ba924a391e91f4ba9a5f9058ad32362f0315160b/NIFTI_NORDIC.m#L1036-L1040

Conversely, for the MP-PCA denoising (when `soft_thrs == 10`), you have the following:

https://github.com/SteenMoeller/NORDIC_Raw/blob/ba924a391e91f4ba9a5f9058ad32362f0315160b/NIFTI_NORDIC.m#L1077-L1079

As far as I can tell, `t` is only used for the SNR calculation, so it shouldn't affect the denoising itself.

**Comment by SteenMoeller** [comment]
If one wants to keep track of the number of singular values retained that may be useful. For fMRI applications, where an uncertainty is often used, knowing the degrees of freedom may be helpful. This indeed has no impact on the denoising itself.
