### ISSUE TITLE
Unable to run DEMO: Undefined function or variable 'subfunction_loop_for_NVR_avg_update'

### ISSUE THREAD

**Issue by CesarCaballeroGaudes** [SteenMoeller/NORDIC_Raw#3]
Hello, 

I'm trying to run the DEMO as indicated in the README.md (also at the end of script_for_creating_simulation_data.m). However, when running NORDIC, I get the following error. Do you know what is happening?

Thanks very much
Cesar

>> NORDIC('demo_data_for_NORDIC.mat')
Using the NVR estimation method

PP = 

       name: 'demo_data_for_NORDIC.mat'
       date: '10-Sep-2021 15:54:45'
      bytes: 204721995
      isdir: 0
    datenum: 7.3841e+05

kernel_size =

     8     8     8

CHECK if the right input to NORDIC is used
change the scaling to the recon program

ans =

    0.4117    0.4020

I am master, I have control
1 Undefined function or variable 'subfunction_loop_for_NVR_avg_update'.

Error in NORDIC>sub_NVR_for_one_slice (line 535)
                     subfunction_loop_for_NVR_avg_update(KSP2a,ARG.kernel_size(3),ARG.kernel_size(2),ARG.kernel_size(1),lambda,1,ARG.soft_thrs,KSP2_weight_tmp,ARG,NOISE_tmp,Component_threshold_tmp,energy_removed_tmp);
                     
Error in NORDIC>NVR_LLR_3D_MP_2 (line 253)
     [KSP_recon,~,KSP_weight,NOISE,Component_threshold,energy_removed]=sub_NVR_for_one_slice(KSP_recon,KSP2,ARG,n1,QQ,master_fast,KSP_weight,NOISE,Component_threshold,energy_removed)
     ;    % save all files

Error in NORDIC (line 23)
NVR_LLR_3D_MP_2(DIR,file_filter,file_idx,NORDIC_threshold,DUAL,kernel_size,patch_avg,['kernel_' num2str(ker)],restart_list, master_fast,soft_thrs,
patch_avg_sub);

**Comment by SteenMoeller** [comment]
I will look at it right away, and sorry about that

Steen

**Comment by SteenMoeller** [comment]
I am very sorry, but the function was missing. I have added it into the
current NORDIC.m file, so please download it again.

Not that it matters, but when I had tested it for deployment, my plain
matlab version had an unintended link to a directory such that I missed the
dependency.

Steen

**Comment by CesarCaballeroGaudes** [comment]
Thanks I will download it and let you know.
