### ISSUE TITLE
function or variable sq in DEMO commands

### ISSUE THREAD

**Issue by CesarCaballeroGaudes** [SteenMoeller/NORDIC_Raw#4]
Hello Steen,
I'm trying to run the DEMO commands as follows, but got an error with the sq function. What's the function or variable sq? 
It might be possible that I am using a very old matlab version, but I could not find any function in Mathworks online help.
Thanks very much,
Cesar

script_for_creating_simulation_data
NORDIC('demo_data_for_NORDIC.mat')
    
QQ=load('KSP_demo_data_for_NORDICkernel8')
Q=load('demo_data_for_NORDIC') 
figure; clf
subplot(2,2,1); imagesc(sq(real(Q.KSP(:,:,32,12))),[0 1]); title('Data + noise')
subplot(2,2,2); imagesc(sq(real(Q.IMG(:,:,32,12))),[0 1]); title('Data w/o noise')
subplot(2,2,3); imagesc(sq(real(QQ.KSP_update(:,:,32,12))),[0 1]); title('NORDIC processed')
subplot(2,2,4); plot(sq(real(Q.KSP(20,25,32,1:end-2)  -   Q.IMG(20,25,32,1:end-1)))), hold on
plot(sq(real(QQ.KSP_update(20,25,32,1:end)  -   Q.IMG(20,25,32,1:end-1))))
legend('difference before NORDIC','difference after NORDIC')

Undefined function 'sq' for input arguments of type 'double'.

**Comment by SteenMoeller** [comment]
I had not thought about that.

sq is just short for squeeze, and something that I made 20 years ago, when
I thought that was a good idea.

I will update the demo example accordingly. I think I have it in all my
Matlab versions and that is why it was missed too.

**Comment by CesarCaballeroGaudes** [comment]
thank you for the clarification
