### ISSUE TITLE
Error in estimating gfactor map

### ISSUE THREAD

**Issue by magrenimish** [SteenMoeller/NORDIC_Raw#6]
Hi there,
Thank you for the work. I tried to run the NIFTI_NORDIC script with diff_MRI related magnitude and phase data, but I keep getting the sum(gfactor(:)) = 0 and therefore an incorrect estimation of the gfactor map. Could you help please?
Thank you

**Comment by SteenMoeller** [comment]
My guess would be that there is a data input format issue. Can you email me on moell018@umn.edu, and we can figure it out, and we can add the solution here.
